services:
  - type: web
    name: plant-disease-detection
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -c "import torch; print('PyTorch version:', torch.__version__)"
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true 